### ISSUE TITLE
numbers JS tutorial

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMeJavaScriptLikeIm5#13]
Populate JS file with a tutorial and challenge.

Note : 
The purpose is to know how to create a number and all types of number it exists etc.

**Comment by sabderemane** [comment]
@Zentreax exactly, it should cover how to define a number, what type of number you can create (integer, float, negative...), some specific element to know about (NaN for example)

Hope that helps!

**Comment by Raghav-Modani** [comment]
Hello! I would like to work on this. Can you assign this to me?

**Comment by sabderemane** [comment]
@Zentreax , should I assigned to you this one? or it will be assigned to @Raghav-Modani

**Comment by sabderemane** [comment]
@Raghav-Modani do you still want to be assigned on it ?

**Comment by Raghav-Modani** [comment]
Yes! I would like to work on this.

**Comment by sabderemane** [comment]
@Raghav-Modani you're assigned now !
