### ISSUE TITLE
while-loops JS tutorial

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMeJavaScriptLikeIm5#25]
Populate JS file with a tutorial and challenge.

**Comment by beheradibas** [comment]
Feel free to assign me. w3School seems to have the beginner-friendly content similar to what you are developing. So , would it be okay to reference their page for a tutorial?

**Comment by funbeedev** [comment]
@beheradibas you're assigned now.
Your submitted tutorial can reference the w3school tutorials but should not be an exact copy, thanks!

**Comment by dilroseR** [comment]
If this is not done, Can I take this up under hacktoberfest 2021?

**Comment by funbeedev** [comment]
@beheradibas Not sure if you still intended to work on this but you can still submit a PR on this issue! If you do we can rename your tutorial file and the repo will have 2 tutorials on while-loops.
