### ISSUE TITLE
indexing-arrays.js

### ISSUE THREAD

**Issue by SaulMiquilena** [inspirezonetech/TeachMeJavaScriptLikeIm5#38]
**Description of the tutorial**
Understand how arrays are indexed.

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
...

**Comment by funbeedev** [comment]
@SaulMiquilena Label added.

**Comment by SaulMiquilena** [comment]
Can this one be merged
