### ISSUE TITLE
[tutorial] Switch 

### ISSUE THREAD

**Issue by pushpit-J19** [inspirezonetech/TeachMeJavaScriptLikeIm5#59]
**Description of the tutorial**
A tutorial on switch conditionals in Javascript

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
Please assign me this issue under Hacktoberfest

**Comment by pushpit-J19** [comment]
@funbeedev kindly assign me this issue

**Comment by funbeedev** [comment]
@pushpit-J19 Sorry but this doesn't add anything new for this repo. Thanks for your suggestion though!
