### ISSUE TITLE
[tutorial] Hoisting, short-circuit evaluation and some other common functions

### ISSUE THREAD

**Issue by nobalpha** [inspirezonetech/TeachMeJavaScriptLikeIm5#62]
**Description of the tutorial**
Hoisting, short-circuit evaluation and some other common functions (like apply, bind, call, reduce, filter)

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
I hope that I don't spam those ideas at once. Also, I know that those aren't really "essential" for a beginner to learn first, but I find them quite useful in shortening the code and debugging efficiently.

**Comment by sabderemane** [comment]
Hi @nobalpha, I think filter can be useful in manipulating-advanced-objects but the purpose of this repo is to explain for a begginner but IMO major part you have said is too advance for this repo. I'm closing the issue.
