### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by sabderemane** [inspirezonetech/TeachMeJavaScriptLikeIm5#63]
**Description**
Update the README.md to see all available tutorials and have links to go directly to the corresponding tutorials.

**Do you want to be assigned to work on this?**
(mark [x])
- [ ] YES
- [x] NO

**Optional: Any additional info you want to add**
...

**Comment by franklinshera** [comment]
Yes I can work on this

**Comment by sabderemane** [comment]
You're assigned now @franklinshera :)
