### ISSUE TITLE
[tutorial] Arrow function

### ISSUE THREAD

**Issue by sabderemane** [inspirezonetech/TeachMeJavaScriptLikeIm5#65]
**Description of the tutorial**
Add a tutorial and challenge for arrow function in functions section (8-functions)

**Do you want to be assigned to work on this?**
(mark [x])
- [ ] YES
- [x] NO

**Optional: Any additional info you want to add**
...

**Comment by thechangamunda** [comment]
I would like to work on it, assign me this issue.
And how long or in debt would you like the intro/tutorial to be,
for example:
I could explain the type of functions and 
then the arrow function,
then its pros and cons/ its applications,
or 
I could explain the basics, provide the resources I am using to make it and continue with some challenge questions.

**Comment by sabderemane** [comment]
> I would like to work on it, assign me this issue.

Done ! 

> I could explain the type of functions and
> then the arrow function,
> then its pros and cons/ its applications,

Sounds good to me, especially the difference with a basic function. There is also a tutorial on functions you can also linked to it to review basic function for example and avoid too many explanation ([tutorial link](https://github.com/inspirezonetech/TeachMeJavaScriptLikeIm5/blob/main/8-functions/functions.js))
