### ISSUE TITLE
[tutorial] JavaScript Exercise for Beginners

### ISSUE THREAD

**Issue by Morbius00** [inspirezonetech/TeachMeJavaScriptLikeIm5#72]
<img src="https://img.shields.io/badge/hacktoberfest-2022-blueviolet" alt="Hacktober Badge"/>

**Description of the tutorial
 JavaScript exercises from books e.g. Eloquent JavaScript, JavaScript and JQuery), code challenges or code mastery sites (e.g. CodeWars, LeetCode, Interview Cake).
# content
* Challenges
* Code wars
* Examples 
* Docs
* tests
**Do you want to be assigned to work on this?**

- [X] YES
- [ ] NO

**Optional: Any additional info you want to add**
...
please assigned me for it  I hope that you will like my project file
Regards,

**Comment by sabderemane** [comment]
Hi @Morbius00 , I'm not sure to understand what will be tutorial in this case if it's only exercises.

**Comment by Morbius00** [comment]
> Hi @Morbius00 , I'm not sure to understand what will be tutorial in this case if it's only exercises.

Well there are lot of tutorial in you repo regarding JS 
But to there is no Js exercise folder is to utilise those tutorial what they learned that's why I want add this....And I hope you will like it.

**Comment by sabderemane** [comment]
> But to there is no Js exercise folder is to utilise those tutorial
There are exercises in comment at the end of each tutorial, since there is no tutorial in this issue, I'm closing it.
