### ISSUE TITLE
[tutorial] do-while loop 

### ISSUE THREAD

**Issue by Parth-ops** [inspirezonetech/TeachMeJavaScriptLikeIm5#73]
**Description of the tutorial**
- What is a do...while loop
- How it is different from while loop
- Few basic questions on do...while loop

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
- [x] I've read the CONTRIBUTING.md

**Comment by Parth-ops** [comment]
@sabderemane could you please assign me for this issue and also label this issue as "good-first" and "hacktoberfest"?

**Comment by sabderemane** [comment]
You're assigned now @Parth-ops !

**Comment by Saurav013** [comment]
Hey @Parth-ops , I would like to contribute in this task, Could you assign me in this please.. I will give my best

**Comment by Parth-ops** [comment]
@Saurav013 I am already working on this and have already submitted a PR.
