### ISSUE TITLE
I will improve an existing tutorial of array with adding some properties or methods of it.

### ISSUE THREAD

**Issue by rishabh1911007** [inspirezonetech/TeachMeJavaScriptLikeIm5#77]
**Description**
I will improve an existing tutorial of array with adding some properties or methods of it.

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
I've read the CONTRIBUTING.md

**Comment by rishabh1911007** [comment]
Could you please assign me for this issue and also label this issue as "good-first" and "hacktoberfest"?

**Comment by sabderemane** [comment]
Done @rishabh1911007 😄

**Comment by rishabh1911007** [comment]
Thanx🤝🏻

**Comment by rishabh1911007** [comment]
Please do check on my pull request and please lablel it with Hacktoberfest-Accepted
