### ISSUE TITLE
[tutorial] If-else statement

### ISSUE THREAD

**Issue by Dancentcee** [inspirezonetech/TeachMeJavaScriptLikeIm5#78]
**Description of the tutorial**
. What is an if-else statement
. How to declare an if-else statement
. A few examples and tasks

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
... Everything is pretty much covered

**Comment by sabderemane** [comment]
There is already a tutorial for that : https://github.com/inspirezonetech/TeachMeJavaScriptLikeIm5/blob/main/6-conditions/conditions.js

Except if you see some improvements to do, I'm closing the issue.
