### ISSUE TITLE
[tutorial] Higher Order Functions - map, filter and reduce.

### ISSUE THREAD

**Issue by Parth-ops** [inspirezonetech/TeachMeJavaScriptLikeIm5#83]
**Description of the tutorial**
-  What are higher order functions.
-  What is the need for higher order functions.
-  Basic difference between the three higher functions - map, filter and reduce.
-  Use cases for each function. (program)
-  Simple challenges to practice these functions.

**Do you want to be assigned to work on this?**

- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
None

**Comment by sabderemane** [comment]
Beware there is also a tutorial about [built-in-functions](https://github.com/inspirezonetech/TeachMeJavaScriptLikeIm5/blob/main/9-common-built-in-functions/built-in-functions.js), to not make conflict with it

**Comment by Parth-ops** [comment]
Sure. I'm planning to add this tutorial under section 8- functions as it would be easy for the learners to grasp it while learning about functions itself and won't cause any conflict with the existing tutorial on built-in-functions.
