### ISSUE TITLE
[tutorial] For Of loop

### ISSUE THREAD

**Issue by Parth-ops** [inspirezonetech/TeachMeJavaScriptLikeIm5#85]
**Description of the tutorial**
- Definition of for...of loop
- Difference between for and for...of loop
- Examples explaining the working of for...of loop
- Basic challenges using for...of loop

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
None

**Comment by sabderemane** [comment]
You're assigned now @Parth-ops 🎉
